export const SETTINGS_CHANGE_START_DATE = 'SETTINGS_CHANGE_START_DATE';
export const SETTINGS_CHANGE_NAME = 'SETTINGS_CHANGE_NAME';

export const NAV_SETTINGS = 'NAV_SETTINGS';
export const NAV_MYSTATS = 'NAV_MYSTATS';
export const NAV_DIETPLAN = 'NAV_DIETPLAN';
export const NAV_FOODMENU = 'NAV_FOODMENU';