// Main App Navigation via bottom menu bar
export const MAIN_LOCATION_SETTINGS = 'MAIN_LOCATION_SETTINGS';
export const MAIN_LOCATION_MYSTATS = 'MAIN_LOCATION_MYSTATS';
export const MAIN_LOCATION_DIETPLAN = 'MAIN_LOCATION_DIETPLAN';
export const MAIN_LOCATION_FOODMENU = 'MAIN_LOCATION_FOODMENU';